CREATE TABLE IF NOT EXISTS clientes (
                                        id SERIAL PRIMARY KEY,
                                        name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phoneNumber VARCHAR(15) NOT NULL
    );

INSERT INTO clientes (name, email, phoneNumber) VALUES
                                                    ('João Silva', 'joao.silva@email.com', '(11) 98765-4321'),
                                                    ('Maria Oliveira', 'maria.oliveira@email.com', '(21) 99876-5432'),
                                                    ('Carlos Souza', 'carlos.souza@email.com', '(31) 91234-5678'),
                                                    ('Ana Costa', 'ana.costa@email.com', '(41) 96789-1234'),
                                                    ('Paulo Pereira', 'paulo.pereira@email.com', '(51) 99887-6543'),
                                                    ('Fernanda Santos', 'fernanda.santos@email.com', '(61) 99865-4321'),
                                                    ('Luiz Almeida', 'luiz.almeida@email.com', '(71) 98754-3210'),
                                                    ('Letícia Rocha', 'leticia.rocha@email.com', '(81) 99843-2109'),
                                                    ('Roberto Martins', 'roberto.martins@email.com', '(91) 98765-4321'),
                                                    ('Juliana Ferreira', 'juliana.ferreira@email.com', '(11) 96543-2109'),
                                                    ('Gustavo Lima', 'gustavo.lima@email.com', '(21) 94321-8765'),
                                                    ('Mariana Alves', 'mariana.alves@email.com', '(31) 97865-4321'),
                                                    ('Ricardo Oliveira', 'ricardo.oliveira@email.com', '(41) 95763-2109'),
                                                    ('Priscila Mendes', 'priscila.mendes@email.com', '(51) 94456-7890'),
                                                    ('Felipe Souza', 'felipe.souza@email.com', '(61) 92765-4310'),
                                                    ('Carolina Costa', 'carolina.costa@email.com', '(71) 91234-5678'),
                                                    ('André Barbosa', 'andre.barbosa@email.com', '(81) 93210-6543'),
                                                    ('Vanessa Pereira', 'vanessa.pereira@email.com', '(91) 90123-4567'),
                                                    ('Fabio Santos', 'fabio.santos@email.com', '(11) 91345-6789'),
                                                    ('Tatiane Rodrigues', 'tatiane.rodrigues@email.com', '(21) 96543-2109'),
                                                    ('João Pedro Silva', 'joao.pedro@email.com', '(11) 96321-8765'),
                                                    ('Gabriela Martins', 'gabriela.martins@email.com', '(21) 91543-2109'),
                                                    ('Henrique Almeida', 'henrique.almeida@email.com', '(31) 98456-7890'),
                                                    ('Mariana Souza', 'mariana.souza@email.com', '(41) 96123-4567'),
                                                    ('Thiago Costa', 'thiago.costa@email.com', '(51) 91234-5678'),
                                                    ('Larissa Rocha', 'larissa.rocha@email.com', '(61) 98765-4321'),
                                                    ('Daniel Ferreira', 'daniel.ferreira@email.com', '(71) 94567-1234'),
                                                    ('Camila Oliveira', 'camila.oliveira@email.com', '(81) 92456-7890'),
                                                    ('Rafael Mendes', 'rafael.mendes@email.com', '(91) 93874-2109'),
                                                    ('Beatriz Pereira', 'beatriz.pereira@email.com', '(11) 95321-4321'),
                                                    ('Gustavo Rodrigues', 'gustavo.rodrigues@email.com', '(21) 96765-4321'),
                                                    ('Letícia Lima', 'leticia.lima@email.com', '(31) 96543-2109'),
                                                    ('Felipe Martins', 'felipe.martins@email.com', '(41) 92234-5678'),
                                                    ('Bruna Costa', 'bruna.costa@email.com', '(51) 98653-2109'),
                                                    ('Jorge Barbosa', 'jorge.barbosa@email.com', '(61) 93123-4567'),
                                                    ('Raquel Almeida', 'raquel.almeida@email.com', '(71) 91567-8901'),
                                                    ('André Lima', 'andre.lima@email.com', '(81) 95321-7654'),
                                                    ('Aline Santos', 'aline.santos@email.com', '(91) 96743-2109'),
                                                    ('Luciano Rocha', 'luciano.rocha@email.com', '(11) 97321-6543'),
                                                    ('Vanessa Alves', 'vanessa.alves@email.com', '(21) 95765-4321');
