version: '3.8'

services:
  frontend:
    build: ./desafio-web
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./desafio
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/desafiodb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234567
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: desafiodb
      MYSQL_ROOT_PASSWORD: 1234567
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
